use_optuna: False

log_dir: ./tmp
video_dir: ${log_dir}/videos

optuna:
      study:
        _target_: optuna.create_study
        study_name: ac_maze
        direction: maximize
        # for a list of optuna pruners, this is here: https://optuna.readthedocs.io/en/stable/reference/pruners.html
        pruner:
          _target_: optuna.pruners.MedianPruner
          n_startup_trials: 5
          n_warmup_steps: 5
          interval_steps: 1
      optimize:
        n_trials: 50 # this value will be overwritten
        timeout: 3600
        n_jobs: 1

sample_size: 5 # number of values to try for alpha actor and alpha critic
nb_episodes: 100
timeout: 200
render: False
nb_repeats: 10
filename: ./perf.data
init_filename: ./perf
save_perf: True
save_learning_curve: False

alpha_actor:
  suggest_type: float
  low: 0.1
  high: 1.0

alpha_critic:
  suggest_type: float
  low: 0.1
  high: 1.0
