    save_best: True
    plot_agents: False

    log_dir: ./tmp
    video_dir: ${log_dir}/videos

    hydra:
      run:
        dir: ${log_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

    logger:
      classname: bbrl.utils.logger.WandbLogger
      project: "td3_study"
      group: "tune_td3"
      tags: "hp_td3"
      job_type: test
      log_dir: ${log_dir}
      cache_size: 10000
      every_n_seconds: 10
      verbose: False

    algorithm:

      seed:
        train: 2
        eval: 9
        q: 1
        act: 2
        explorer: 4
        torch: 7

      n_envs: 1
      n_steps_train: 100
      n_steps: 70000
      buffer_size: 10e6
      tau_target: 0.005
      optim_n_updates: 1
      eval_interval: 2500
      learning_starts: 10000
      nb_evals: 1
      max_grad_norm: 0.5
      batch_size: 100
      action_noise: 0.1
      discount_factor: 0.9999
      architecture:
        actor_hidden_size: [256, 256]
        critic_hidden_size: [256, 256]

    gym_env:
      env_name: RocketLander-v0

    actor_optimizer:
      classname: torch.optim.Adam
      lr: 0.001
    
    critic_optimizer:
      classname: torch.optim.Adam
      lr: 0.001
